void initFrog();
void updateFrog(int input, int);
void checkCollision();
void checkFloat();
int checkFloatValue(int i);
int checkCollisionValue(int i);
int getLeaderIndex();
int checkFor();
int checkFrogPosition(int direction);
void updateFloatingFrog(int i);
